export const enum ROUTES {
  HOME = '/',
  LIBRARY = '/library',
  SEARCH = '/search',
  NEW_SEARCH = '/new-search',
  NAMES = '/names',
}

export const enum GENDER {
  BOY = 'boy',
  GIRL = 'girl',
  BOTH = 'both',
  NONE = 'none',
}

export const enum FILTERS {
  BOY = 'boy',
  GIRL = 'girl',
  LIKED = 'liked',
  DISLIKED = 'disliked',
}

export const ORIGIN_MAP: Record<string, string> = {
  Dutch: '🇳🇱',
  Scandinavia: '🇸🇪',
  Spanish: '🇪🇸',
  Indian: '🇮🇳',
  Arabic: '🇸🇦',
  Rome: '🇮🇹',
  'Scottish/Irish': '🇬🇧',
  'Spanish/Portuguese': '🇪🇸',
  Hawaiian: '🇺🇸',
  Celtic: '🇮🇪',
  Unknown: '❓',
  Irish: '🇮🇪',
  French: '🇫🇷',
  Thai: '🇹🇭',
  'Germany/Poland': '🇩🇪',
  Russian: '🇷🇺',
  Polish: '🇵🇱',
  Igbo: '🇳🇬',
  Persian: '🇮🇷',
  Croatian: '🇭🇷',
  Norwegian: '🇳🇴',
  Egypt: '🇪🇬',
  India: '🇮🇳',
  Latin: '🏳',
  'South Africa': '🇿🇦',
  English: '🇬🇧',
  Denmark: '🇩🇰',
  Greek: '🇬🇷',
  Turkey: '🇹🇷',
  Swahili: '🇹🇿',
  Turkish: '🇹🇷',
  'New Zealand': '🇳🇿',
  'Ancient Rome': '🇮🇹',
  Scandinavian: '🇸🇪',
  Africa: '🌍',
  American: '🇺🇸',
  Russia: '🇷🇺',
  Norse: '🇳🇴',
  'Greek mythology': '🇬🇷',
  Japanese: '🇯🇵',
  Israeli: '🇮🇱',
  Aramaic: '🏳',
  Hebrew: '🇮🇱',
  Sanskrit: '🇮🇳',
  Basque: '🇪🇸',
  Spain: '🇪🇸',
  German: '🇩🇪',
  Somali: '🇸🇴',
  Italian: '🇮🇹',
  Scottish: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  African: '🌍',
  Swedish: '🇸🇪',
  Finnish: '🇫🇮',
  Roman: '🇮🇹',
  Portuguese: '🇵🇹',
  Hindi: '🇮🇳',
  Slavic: '🇷🇺',
  Poland: '🇵🇱',
  'Native American': '🪶',
  Romanian: '🇷🇴',
  Austrian: '🇦🇹',
  Serbian: '🇷🇸',
  Hindu: '🇮🇳',
  Welsh: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  Various: '🏳',
};
